### ISSUE TITLE
Import Brazil—Paraiba case data

### ISSUE THREAD

**Issue by iamleeg** [globaldothealth/list#499] opened 2020-07-09 15:39 UTC
https://superset.plataformatarget.com.br/superset/dashboard/microdados/

**Comment by z023** [comment] 2020-09-20 22:11
Paraiba data not being ingested.

**Comment by attwad** [comment] 2020-09-21 09:13
I'm seeing `time data 'Swab' does not match format '%Y-%m-%d'` in the logs, and indeed there are a lot of 'Swab' in the CSV, Anya the parser should account for it please.

**Comment by AnyaLindstromBattle** [comment] 2020-09-23 15:55
@z023 Changed some stuff in Paraiba parser, please let me know if still not ingesting.

**Comment by z023** [comment] 2020-09-23 21:21
Thanks Anya. Still not ingesting though.

**Comment by AnyaLindstromBattle** [comment] 2020-09-23 21:28
Strange - same error in the logs?

**Comment by z023** [comment] 2020-09-23 21:35
<img width="1037" alt="Screenshot 2020-09-23 at 22 34 29" src="https://user-images.githubusercontent.com/65172419/94072143-0d462a00-fded-11ea-9747-989e2b6b633f.png">

**Comment by attwad** [comment] 2020-09-24 06:26
Error seems unrelated to Paraiba:

```
[ERROR] KeyError: 'dateRange'
Traceback (most recent call last):
  File "/var/task/paraiba.py", line 190, in lambda_handler
    return parsing_lib.run_lambda(event, context, parse_cases)
  File "/opt/python/parsing_lib.py", line 291, in run_lambda
    common_lib.complete_with_error(
  File "/opt/python/common_lib.py", line 98, in complete_with_error
    raise exception
  File "/opt/python/parsing_lib.py", line 276, in run_lambda
    count_created, count_updated = write_to_server(
  File "/opt/python/parsing_lib.py", line 120, in write_to_server
    batch = batch_of(cases, cases_batch_size)
  File "/opt/python/parsing_lib.py", line 104, in batch_of
    batch.append(next(cases))
  File "/opt/python/parsing_lib.py", line 214, in <genexpr>
    return (case for case in case_data if case_is_within_range(case, cutoff_date, op))
  File "/opt/python/parsing_lib.py", line 202, in case_is_within_range
    confirmed_event["dateRange"]["start"], DATE_FORMAT)
```

that might be related to a PR @axmb sent yesterday for backfilling data, I will look into this now.

**Comment by attwad** [comment] 2020-09-24 06:30
Ah no that's expected, Paraiba doesn't have a confirmed date case

```
"events": [
                    {
                        "name": "confirmed",
                        "value": convert_confirmation_method(row[_METHOD_CONFIRMATION])
                    },
```

so we can't filter by dates... Because Paraiba doesn't have unique case IDs either we don't have a procedure to automatically ingest that source besides ingesting it once and not periodically :-(

@axmb your thoughts on this?

**Comment by iamleeg** [comment] 2020-09-24 14:36
Maybe above and beyond for an early importer but some options to work around the lack of IDs:

1. they might be appending new cases to the top or bottom of the file, if we can compare files from different dates and see the diff it might be obvious that we can use a cursor-based approach.

2. I'm not sure how to integrate this into our architecture but the parser could be stateful and build a histogram of cases. If it's already got one case for a given (age, death date, onset date, sex, method, municipality, preexisting conditions) tuple and finds two this time, it needs to create a new line.

Neither of these are robust though, as they don't account for lines being updated in the data, so I guess we need to know if/how often that happens too.

**Comment by AnyaLindstromBattle** [comment] 2020-09-24 15:08
I have a suggestion - @Mougk made me aware of an alternative Brazilian state dataset a few days ago which, for Paraiba, actually has both a UUID and a date of confirmation. I could re-write the parser for this dataset if we think other solutions are infeasible/too complicated? Dataset here https://opendatasus.saude.gov.br/dataset/casos-nacionais

**Comment by attwad** [comment] 2020-09-24 15:10
> I have a suggestion - @Mougk made me aware of an alternative Brazilian state dataset a few days ago which, for Paraiba, actually has both a UUID and a date of confirmation. I could re-write the parser for this dataset if we think other solutions are infeasible/too complicated? Dataset here https://opendatasus.saude.gov.br/dataset/casos-nacionais

If it has unique IDs then it's 200% preferred to use that dataset! Hope the rewrite isn't too cumbersome.

**Comment by AnyaLindstromBattle** [comment] 2020-09-24 15:12
Should be fine, will get to it ASAP!

**Comment by AnyaLindstromBattle** [comment] 2020-10-23 17:33
@iamleeg To follow up on my slack message, the re-write I mentioned above has been done. I.e. the current Paraiba parser has been re-written to parse data from the new URL above. Guess this is a point when opening/closing issues as we discussed would have been useful to maker what has and hasn't been done clearer.

**Comment by AnyaLindstromBattle** [comment] 2020-10-23 17:49
See #1269

**Closed** 2020-12-02 10:44 UTC
Labels: Importer
