### ISSUE TITLE
Usability issue: Entering new source URL

### ISSUE THREAD

**Issue by sratcliffe118** [globaldothealth/list#630] opened 2020-07-27 10:14 UTC
Issue: It was unclear that after copying the source into the field, the you need to click just below it in order to actually successfully enter the source. Led to multiple efforts. "I didn't realize I had to select it" (In order to "add new source") 

![Screen Shot 2020-07-27 at 11 12 30 AM](https://user-images.githubusercontent.com/63205311/88531140-4aaf5680-cffa-11ea-9a95-538322ddecd3.png)

**Comment by allysonjp715** [comment] 2020-07-27 10:20
We can change this so that you don't have to click the option.

**Comment by sratcliffe118** [comment] 2020-07-27 11:42
SGTM

**Comment by allysonjp715** [comment] 2020-07-30 09:47
Duplicate of #632

**Closed by allysonjp715** 2020-07-30 09:47 UTC
Labels: Curator Portal, P1 Launch blocker, UX Behaviour
