### ISSUE TITLE
Support multiple query levels for regional map filtering

### ISSUE THREAD

**Issue by calremmel** [globaldothealth/list#1602] opened 2021-02-23 17:34 UTC
While I had initially thought that the `administrativeLevel3` field was usually populated, it turns out that this is not the case, and that aggregating counts by that field introduces errors. The result is that clicking "Explore Regional Data" doesn't return results if `administrativeLevel3` does not have an entry.

As part of a solution, I have reworked the aggregate pipeline to return the most granular available field, and have included a new field called `search_term` that contains what that field is, possibilities being `admin1/2/3` or `country`.

Here is what would need to be implemented to make best use of this:

- [x] If `search_term` contains `admin1` / `admin2` / `admin3`, pass through `country: record["country"] search_term: record["_id"]` to the Data search field
- [x] If `search_term` contains `country`, pass through only `country: record["country"]`
- [x] Instead of passing in only the most specific filter level, pass in all filter levels available

**Comment by calremmel** [comment] 2021-02-24 17:11
Part 2!

**Bug:**

If a particular level i.e. admin2:"Clark County" exists for multiple higher levels, i.e. admin1:"Washington" admin1:"Nevada", the current solution will return results for all Clark County instances.

**Proposed Solution**

Instead of passing in only the most specific filter level, pass in all filter levels available. i.e.:

before: `admin2:"Clark County"`
after: `country:"United States" admin1:"Washington" admin2:"Clark County"`

@rkassa Just let me know if it would be helpful to have the query strings generated on the backend, and maybe an example desired value if so?

**Comment by joe-brilliant** [comment] 2021-03-01 21:59
@calremmel can we close this ?

**Comment by calremmel** [comment] 2021-03-01 22:35
@joe-brilliant This one still needs doing! This is what will solve the "all the Clark Counties show up when you click on any on the Map" bug. It is a frontend fix primarily, with backend support if needed.

**Comment by joe-brilliant** [comment] 2021-03-02 04:29
Thanks @calremmel ! I'll move to post launch

**Comment by sergioloporto** [comment] 2021-04-06 15:11
Unfortunately I can't work on it anymore since the map is not showing up.
Thanks to @rkassa for his remote support on it, but unfortunately we couldn't find the root cause of the issue.

The issue is free to be taken.

**Closed** 2022-02-22 10:07 UTC
Labels: Data, P1: Launch blocker, Visualizations, React rebuild, HTD
