### ISSUE TITLE
'Events' columns empty in line list download

### ISSUE THREAD

**Issue by z023** [globaldothealth/list#1380] opened 2020-11-30 19:10 UTC
When downloading data from the UI line list all the events columns are empty so no confirmation date or hospital admissions etc. are coming through. Could have been an issue when the events column was re-configured to separate columns?

**Comment by calremmel** [comment] 2020-11-30 23:44
@rpoltorak Hi Remek! What do you think about this? Is this just because we haven't pushed some crucial piece to production?

**Comment by rpoltorak** [comment] 2020-12-01 00:32
@calremmel First thing that comes to my mind is that:
1. We've changed that file: https://github.com/globaldothealth/list/blob/main/data-serving/scripts/export-data/case_fields.yaml which is responsible for specifying which fields should be taken into account while exporting. 
2. The problem is that the backend (data-service) and mongo script uses the direct link from the GitHub (mentioned above). For example here: https://github.com/globaldothealth/list/blob/f0421d46765fbf02bb3b50a69832b1de47fbc91f/data-serving/data-service/src/controllers/case.ts#L70 
So this is not working because the current changes weren't deployed. To fix this we need to create a release or I can revert changes in that single file and change it back after the future release.

**Comment by calremmel** [comment] 2020-12-01 21:08
Thanks @rpoltorak! So there's the answer @z023 : this is temporary and will be fixed once we move some of HTD's other fixes to production. May as well keep the issue open for now, but no action needed unless it's still there once we push the new code.

**Closed** 2021-03-05 16:45 UTC
Labels: P1 Launch blocker
