### ISSUE TITLE
Individual cases: Remove list of countries

### ISSUE THREAD

**Issue by dakrownie** [globaldothealth/list#1058] opened 2020-09-16 16:11 UTC
Design link 
Slide 11

[Link to beta testing blockers list](https://docs.google.com/spreadsheets/d/1wM6se-GPNic3xxyggXPEsk0W6qMo6zl_RRcEwU6OcoU/edit#gid=1506108781)

**Comment by sratcliffe118** [comment] 2020-09-16 22:19
Duplicate of #1074

**Closed by sratcliffe118** 2020-09-16 22:19 UTC
Labels: P0: Critical path blocker
