### ISSUE TITLE
Import Japan case data

### ISSUE THREAD

**Issue by iamleeg** [globaldothealth/list#481] opened 2020-07-09 14:57 UTC
https://github.com/reustle/covid19japan-data/tree/master/docs/patient_data

**Comment by attwad** [comment] 2020-09-03 07:33
Looking at the data now, it seems we should be looking at a few more fields to make this parser more useful:

- `confirmedPatient` is true or false, we only want to import the true cases.
- `sourceURL` and `deathSourceURL` should be put as extra sources url in `caseReferences.additionalSources`
- `deceasedDate` should be an event
- `patientStatus` should be parsed as well (I've seen values `Recovered`, `Deceased`)

**Comment by z023** [comment] 2020-09-14 14:56
Japan is only showing ~3k cases and should be showing ~75k cases. A parser issue?
Location admin areas 1, 2 and 3 are coming through still in Japanese.

**Comment by attwad** [comment] 2020-09-15 07:48
The logs of the last run of the parser says that it errored out after having imported 3k cases
![image](https://user-images.githubusercontent.com/1255432/93181246-86cc8100-f738-11ea-9097-6ac97f7e61c1.png)


The parser is fine but the system is having issue that we're tracking in https://github.com/globaldothealth/list/issues/961

**Comment by z023** [comment] 2020-09-16 10:29
Location.name is in English but location.admins are not being translated.

**Comment by attwad** [comment] 2020-09-16 10:30
Cf my other comment for Thailand, this has been fixed.

**Comment by sratcliffe118** [comment] 2020-09-28 15:38
has this issue been resolved?

**Comment by z023** [comment] 2020-09-28 16:07
There are still cases identified at airport quarantine coming through as Indonesia. Might this need to be manually edited?

**Comment by attwad** [comment] 2020-09-28 16:09
Japan has 79963 cases imported which corresponds to the cases in the raw file and the admins are translated yes so I think this can be closed.

**Comment by attwad** [comment] 2020-09-28 16:10
> There are still cases identified at airport quarantine coming through as Indonesia. Might this need to be manually edited?

Yes you can add a notes to these pending https://github.com/globaldothealth/list/issues/1013

**Comment by axmb** [comment] 2020-09-30 15:42
We're getting validation failures for writing this data during backfill:

https://console.aws.amazon.com/cloudwatch/home?region=us-east-1#logsV2:log-groups/log-group/$252Faws$252Flambda$252Fepid-ingestion-JapanParsingFunction-1OQ1QSBLCA0XV/log-events/2020$252F09$252F30$252F$255B$2524LATEST$255D8b6f9542bd36419ca05864fea9e0d4d3$3Fstart$3DPT12H
```
Error sending cases to server, status=500, response={"name":"BulkWriteError","driver":true,"code":121,"writeErrors":[{"code":121,"index":114,"errmsg":"Document failed validation","op":{"q":{"caseReference.sourceId":"5f61fa80361939e32e4c331d","caseReference.sourceEntryId":"1201"},"u":{"$set":{"revisionMetadata":{"revisionNumber":0,"creationMetadata":{"curator":"ingestion@covid-19-map-277002.iam.gserviceaccount.com","date":"2020-09-30T11:46:43.768Z"}},"demographics":{"nationalities":[],"ageRange":{"start":80,"end":89},"gender":"Male"},"events":[{"name":"confirmed","dateRange":{"start":"2020-03-23T00:00:00.000Z","end":"2020-03-23T00:00:00.000Z"}},{"name":"outcome","dateRange":{"start":"2020-03-23T00:00:00.000Z","end":"2020-03-23T00:00:00.000Z"},"value":"Death"}],"location":{"query":"Okazaki, Aichi, Japan","geometry":{"longitude":137.16667,"latitude":34.95},"country":"Japan","place":"","name":"Okazaki Shi, Aichi, Japan","geoResolution":"Admin3","administrativeAreaLevel1":"Aichi","administrativeAreaLevel2":"Aichi","administrativeAreaLevel3":"Okazaki-shi"},"caseReference":{"uploadIds":["5f746fb2b91dfc85534d097b"],"verificationStatus":"UNVERIFIED","sourceId":"5f61fa80361939e32e4c331d","sourceEntryId":"1201","sourceUrl":"https://raw.githubusercontent.com/reustle/covid19japan-data/master/docs/patient_data/2020-09-30.json","additionalSources":[{"sourceUrl":"https://www3.nhk.or.jp/news/html/20200323/k10012345631000.html"},{"sourceUrl":"https://www3.nhk.or.jp/news/html/20200323/k10012345631000.html"}]}}},"multi":false,"upsert":true}}],"result":{"ok":1,"writeErrors":[{"code":121,"index":114,"errmsg":"Document failed validation","op":{"q":{"caseReference.sourceId":"5f61fa80361939e32e4c331d","caseReference.sourceEntryId":"1201"},"u":{"$set":{"revisionMetadata":{"revisionNumber":0,"creationMetadata":{"curator":"ingestion@covid-19-map-277002.iam.gserviceaccount.com","date":"2020-09-30T11:46:43.768Z"}},"demographics":{"nationalities":[],"ageRange":{"start":80,"end":89},"gender":"Male"},"events":[{"name":"confirmed","dateRange":{"start":"2020-03-23T00:00:00.000Z","end":"2020-03-23T00:00:00.000Z"}},{"name":"outcome","dateRange":{"start":"2020-03-23T00:00:00.000Z","end":"2020-03-23T00:00:00.000Z"},"value":"Death"}],"location":{"query":"Okazaki, Aichi, Japan","geometry":{"longitude":137.16667,"latitude":34.95},"country":"Japan","place":"","name":"Okazaki Shi, Aichi, Japan","geoResolution":"Admin3","administrativeAreaLevel1":"Aichi","administrativeAreaLevel2":"Aichi","administrativeAreaLevel3":"Okazaki-shi"},"caseReference":{"uploadIds":["5f746fb2b91dfc85534d097b"],"verificationStatus":"UNVERIFIED","sourceId":"5f61fa80361939e32e4c331d","sourceEntryId":"1201","sourceUrl":"https://raw.githubusercontent.com/reustle/covid19japan-data/master/docs/patient_data/2020-09-30.json","additionalSources":[{"sourceUrl":"https://www3.nhk.or.jp/news/html/20200323/k10012345631000.html"},{"sourceUrl":"https://www3.nhk.or.jp/news/html/20200323/k10012345631000.html"}]}}},"multi":false,"upsert":true}}],"writeConcernErrors":[],"insertedIds":[],"nInserted":0,"nUpserted":249,"nMatched":0,"nModified":0,"nRemoved":0,"upserted":[...]
```

Did we deploy the change reverting to the old upsert mechanism, @allysonjp715 ?
Or perhaps did we introduce a validation issue in a recent parser change, @attwad ?

**Comment by attwad** [comment] 2020-09-30 15:46
yes the change has been deployed, nothing change on the parser's side though.

**Comment by z023** [comment] 2020-10-02 12:29
Any updates on errors?

**Comment by attwad** [comment] 2020-10-02 12:36
This document looks fine, I don't know why such validation error occurs. @AnyaLindstromBattle did they happen locally as well?

```
{
  "revisionMetadata": {
    "revisionNumber": 0,
    "creationMetadata": {
      "curator": "ingestion@covid-19-map-277002.iam.gserviceaccount.com",
      "date": "2020-09-30T11:46:43.768Z"
    }
  },
  "demographics": {
    "nationalities": [],
    "ageRange": {
      "start": 80,
      "end": 89
    },
    "gender": "Male"
  },
  "events": [
    {
      "name": "confirmed",
      "dateRange": {
        "start": "2020-03-23T00:00:00.000Z",
        "end": "2020-03-23T00:00:00.000Z"
      }
    },
    {
      "name": "outcome",
      "dateRange": {
        "start": "2020-03-23T00:00:00.000Z",
        "end": "2020-03-23T00:00:00.000Z"
      },
      "value": "Death"
    }
  ],
  "location": {
    "query": "Okazaki, Aichi, Japan",
    "geometry": {
      "longitude": 137.16667,
      "latitude": 34.95
    },
    "country": "Japan",
    "place": "",
    "name": "Okazaki Shi, Aichi, Japan",
    "geoResolution": "Admin3",
    "administrativeAreaLevel1": "Aichi",
    "administrativeAreaLevel2": "Aichi",
    "administrativeAreaLevel3": "Okazaki-shi"
  },
  "caseReference": {
    "uploadIds": [
      "5f746fb2b91dfc85534d097b"
    ],
    "verificationStatus": "UNVERIFIED",
    "sourceId": "5f61fa80361939e32e4c331d",
    "sourceEntryId": "1201",
    "sourceUrl": "https://raw.githubusercontent.com/reustle/covid19japan-data/master/docs/patient_data/2020-09-30.json",
    "additionalSources": [
      {
        "sourceUrl": "https://www3.nhk.or.jp/news/html/20200323/k10012345631000.html"
      },
      {
        "sourceUrl": "https://www3.nhk.or.jp/news/html/20200323/k10012345631000.html"
      }
    ]
  }
}
```

**Comment by AnyaLindstromBattle** [comment] 2020-10-02 13:10
Nope, everything passed e2e. Will check that is still the case but to my knowledge haven't changed the parser since #1147. Did it work before then?

**Comment by z023** [comment] 2020-10-02 13:30
Yes Japan was working fine up until last Friday 25th it looks like.

**Comment by AnyaLindstromBattle** [comment] 2020-10-02 13:35
OK the update was merged 24th 15.31 BST, when was the last run that worked?

**Comment by z023** [comment] 2020-10-02 13:45
Looks like 24th was the last success, upload ID 5f6c86d6e09d6f235322615b

**Comment by z023** [comment] 2020-10-05 12:58
Any progress with what's going on here?

**Comment by AnyaLindstromBattle** [comment] 2020-10-05 13:05
Can't check whether I get local validation errors atm as having permission issues, hopefully @attwad can help me solve it. Will try asap once I can access again.

**Comment by AnyaLindstromBattle** [comment] 2020-10-12 13:51
heya - Japan parser seems to work locally. Checked source URL though and looks as though they are different again. This is the one that I was using during local testing: https://data.covid19japan.com/patient_data/latest.json

**Comment by z023** [comment] 2020-10-12 15:30
With the previous source I was using (https://raw.githubusercontent.com/reustle/covid19japan-data/master/docs/patient_data/$FULLYEAR-$FULLMONTH-$FULLDAY.json) we had to add in the date filter into the file name as it was separate files for each day. But looking at the source url you just sent I don't think I need to add that in. I just ran Japan with https://data.covid19japan.com/patient_data/latest.json and got an error 5f84652fb5daec35595d23a7

**Comment by AnyaLindstromBattle** [comment] 2020-10-12 15:44
Hmmm I wonder if it might be because the two additional SourceUrls are the same? @calremmel what do you think? The actual entry looks fine to me.

[
        {
            "code": 121,
            "index": 0,
            "errmsg": "Document failed validation",
            "op": {
                "q": {
                    "caseReference.sourceId": "5f61fa80361939e32e4c331d",
                    "caseReference.sourceEntryId": "1201"
                },
                "u": {
                    "$set": {
                        "revisionMetadata": {
                            "revisionNumber": 0,
                            "creationMetadata": {
                                "curator": "ingestion@covid-19-map-277002.iam.gserviceaccount.com",
                                "date": "2020-10-12T14:17:22.585Z"
                            }
                        },
                        "demographics": {
                            "nationalities": [],
                            "ageRange": {
                                "start": 80,
                                "end": 89
                            },
                            "gender": "Male"
                        },
                        "events": [
                            {
                                "name": "confirmed",
                                "dateRange": {
                                    "start": "2020-03-23T00:00:00.000Z",
                                    "end": "2020-03-23T00:00:00.000Z"
                                }
                            },
                            {
                                "name": "outcome",
                                "dateRange": {
                                    "start": "2020-03-23T00:00:00.000Z",
                                    "end": "2020-03-23T00:00:00.000Z"
                                },
                                "value": "Death"
                            }
                        ],
                        "location": {
                            "query": "Okazaki, Aichi, Japan",
                            "geometry": {
                                "longitude": 137.16667,
                                "latitude": 34.95
                            },
                            "country": "Japan",
                            "place": "",
                            "name": "Okazaki Shi, Aichi, Japan",
                            "geoResolution": "Admin3",
                            "administrativeAreaLevel1": "Aichi",
                            "administrativeAreaLevel2": "Aichi",
                            "administrativeAreaLevel3": "Okazaki-shi"
                        },
                        "caseReference": {
                            "uploadIds": [
                                "5f84652fb5daec35595d23a7"
                            ],
                            "verificationStatus": "UNVERIFIED",
                            "sourceId": "5f61fa80361939e32e4c331d",
                            "sourceEntryId": "1201",
                            "sourceUrl": "https://data.covid19japan.com/patient_data/latest.json",
                            "additionalSources": [
                                {
                                    "sourceUrl": "https://www3.nhk.or.jp/news/html/20200323/k10012345631000.html"
                                },
                                {
                                    "sourceUrl": "https://www3.nhk.or.jp/news/html/20200323/k10012345631000.html"
                                }
                            ]
                        }
                    }
                },
                "multi": false,
                "upsert": true
            }
        }
    ]

**Closed** 2020-12-02 10:44 UTC
Labels: Importer, good first issue
