### ISSUE TITLE
Google Analytics Dashboard w/ Updated Token

### ISSUE THREAD

**Issue by calremmel** [globaldothealth/list#1715] opened 2021-04-06 15:25 UTC

**Comment by rkassa** [comment] 2021-04-29 22:46
@joe-brilliant 
Closing, since it's a duplicate of #1612

**Closed by rkassa** 2021-04-29 22:46 UTC
Labels: P0: Critical path blocker, Website

**Comment by joe-brilliant** [comment] 2021-04-30 16:52
@rkassa does this reflect the new dynamic token I forwarded?
