### ISSUE TITLE
Adjust all typefaces to Inter

### ISSUE THREAD

**Issue by dakrownie** [globaldothealth/list#1060] opened 2020-09-16 16:14 UTC
Notes:
Will align to brand

[Link to beta testing blocker list](https://docs.google.com/spreadsheets/d/1wM6se-GPNic3xxyggXPEsk0W6qMo6zl_RRcEwU6OcoU/edit#gid=1506108781)

**Comment by lmanul** [comment] 2020-09-16 20:50
I would argue font face is not P0? If everything is P0, nothing is ;-P

**Comment by sratcliffe118** [comment] 2020-09-16 22:18
This is duplicate of #1102

Not a P0 either, agreed, 1102 is a P1

**Closed by sratcliffe118** 2020-09-16 22:18 UTC
Labels: P0: Critical path blocker
