### ISSUE TITLE
Search is crashing the app while using the pagination in Line List view

### ISSUE THREAD

**Issue by rpoltorak** [globaldothealth/list#1350] opened 2020-11-10 15:55 UTC
**Describe the bug**
We've found a problem with the line list pagination. It occurs when I switch to a page other than the first one and try to search for something. 

**To Reproduce**
1. Go to the Line List view.
2. Change a page to the second one.
3. Put something in the search input.
4. Hit enter.
5. See the white screen.

**Expected behavior**
A user should be redirected to the first page (or the same that has been selected before) with a search filter applied.

**Environment (please complete the following information):**
 - macOS
 - Google Chrome
 - Version 86.0.4240.183

**Additional context**
Error details: 185: Maximum update depth exceeded

**Developer hint**
Probably some operation in a code related to the search is causing the infinite loop.

**Comment by calremmel** [comment] 2021-03-12 19:31
@WeronikaMichaluk Current status on this is we will want to test to see whether this bug can be reproduced live, close if not, try to address otherwise.

**Comment by WeronikaMichaluk** [comment] 2021-03-13 07:41
@sergioloporto @maciekz1996 as mentioned above 
Current status on this is we will want to test to see whether this bug can be reproduced live, close if not, try to address otherwise.

**Comment by sergioloporto** [comment] 2021-03-13 17:05
@calremmel @WeronikaMichaluk 
I tested on production global.health.

The issue cannot be reproduced.
Everything seems to be working fine.
Closing

**Closed by sergioloporto** 2021-03-13 17:05 UTC
Labels: Data UI, P1 Launch blocker
