### ISSUE TITLE
Filtering by Nationality: American brings back cases with no nationality included 

### ISSUE THREAD

**Issue by sratcliffe118** [globaldothealth/list#1149] opened 2020-09-21 11:27 UTC
**Describe the bug**
Filtering the line list case set by nationality returns cases where there is no nationality set. Appears they may be pulled in because they have American in the notes of the case

Expected behavior should be that only cases with the nationality set as American should be returned

**To Reproduce**
1. Go to the line list
2. Search by nationality: American

**Expected behavior**
Only cases where the nationality is set to American should display. Currently there are none, so no cases should display

**Screenshots**

**Environment (please complete the following information):**

**Additional context**

![Screen Shot 2020-09-21 at 12 24 04 PM](https://user-images.githubusercontent.com/63205311/93761447-b5010380-fc05-11ea-8a86-e4a867a8a279.png)
![Screen Shot 2020-09-21 at 12 26 52 PM](https://user-images.githubusercontent.com/63205311/93761472-bf230200-fc05-11ea-8489-97eb6c864a85.png)

**Comment by attwad** [comment] 2020-09-22 09:40
Dupe of #1156

**Closed by attwad** 2020-09-22 09:40 UTC
Labels: Curator Portal, Data, Eng ready
