### ISSUE TITLE
Mock up and style country zoom

### ISSUE THREAD

**Issue by dakrownie** [globaldothealth/list#1064] opened 2020-09-16 16:18 UTC
[Link to beta testing blocker list](https://docs.google.com/spreadsheets/d/1wM6se-GPNic3xxyggXPEsk0W6qMo6zl_RRcEwU6OcoU/edit#gid=1506108781)

**Comment by dakrownie** [comment] 2020-09-16 16:18
Assigned to tommyshimko@google.com and Manu

**Comment by lmanul** [comment] 2020-09-16 20:49
What is Tommy's Github handle? This probably shouldn't be assigned to me just yet.

**Comment by dakrownie** [comment] 2020-09-17 08:40
I've asked Tommy if he is on Github, and would reassign once I get his handle.

**Comment by sratcliffe118** [comment] 2020-09-22 11:20
@shroothless any update here, please add mock to the issue

**Comment by shroothless** [comment] 2020-09-22 12:45
See hover state [here](https://www.figma.com/file/tfBStxWn2bORj0RyJD0zaB/User-Study-Sept-21?node-id=1%3A843)

![image](https://user-images.githubusercontent.com/67452108/93883675-e2a28700-fcaf-11ea-9c9f-f84ad1a44028.png)

**Comment by lmanul** [comment] 2020-09-29 10:52
This looks the same ass issue #1070 ? The mock is the same.

**Comment by lmanul** [comment] 2020-09-29 10:52
Duplicate of #1070

**Closed by lmanul** 2020-09-29 10:52 UTC
Labels: Eng ready, P1 Launch blocker, Visualizations
