### ISSUE TITLE
Import Germany case data

### ISSUE THREAD

**Issue by iamleeg** [globaldothealth/list#482] opened 2020-07-09 15:03 UTC
https://npgeo-corona-npgeo-de.hub.arcgis.com/datasets/dd4580c810204019a7b8eb3e0b329dd6_0?page=26

**Comment by z023** [comment] 2020-09-18 22:39
Germany isn't being ingested. A parser issue?

**Comment by attwad** [comment] 2020-09-21 09:07
The source configuration was pointing to the download page and not the actual data so the parser wasn't parsing anything indeed.

was: https://www.arcgis.com/home/item.html?id=f10774f1c63e40168479a1feb6c7ca74
should be: https://www.arcgis.com/sharing/rest/content/items/f10774f1c63e40168479a1feb6c7ca74/data

**Comment by attwad** [comment] 2020-09-21 09:07
I've changed it and triggered a retrieval.

**Comment by attwad** [comment] 2020-09-23 08:46
Looking at the ingestion logs, it seems we have issue with geocoding the cases:

```
Error sending cases to server, status=207, response=
{
    "phase": "GEOCODE",
    "numCreated": 0,
    "numUpdated": 0,
    "errors": [
        {
            "index": 0,
            "message": "no geolocation found for Germany, Schleswig-Holstein, SK Flensburg"
        },
        {
            "index": 1,
            "message": "no geolocation found for Germany, Schleswig-Holstein, SK Flensburg"
        },
...
```

I confirmed in their playground that mapbox prefers location to be written as "SK Flensburg, Schleswig-Holstein, Germany" instead.

@calremmel can you fix this please?

**Comment by z023** [comment] 2020-09-25 12:57
Is the geo coding resolved? Germany still isn't ingesting.

**Comment by attwad** [comment] 2020-09-25 13:27
Still some issues with it it seems, let me double check why...

**Comment by attwad** [comment] 2020-09-25 13:35
Hmmm mapbox has no results for "SK Flensburg, Schleswig-Holstein, Germany" when filtered by district (admin 2), it does provide a good one when no restrictions are set however:

```
{"id":"place.6415657628979890","type":"Feature","place_type":["place"],"relevance":0.772222,"properties":{"wikidata":"Q3798"},"text":"Flensburg","place_name":"Flensburg, Schleswig-Holstein, Germany","bbox":[9.357329,54.75195,9.506826,54.82434],"center":[9.43667,54.78194],"geometry":{"type":"Point","coordinates":[9.43667,54.78194]},"context":[{"id":"region.11132476791043490","wikidata":"Q1194","short_code":"DE-SH","text":"Schleswig-Holstein"},{"id":"country.11437281100480410","wikidata":"Q183","short_code":"de","text":"Germany"}]}
```

We could remove the special restriction to admin2 and leave a note in the code, will send a PR to Chris.

**Comment by Mougk** [comment] 2020-09-25 13:37
I think this sounds good.

**Comment by z023** [comment] 2020-09-28 11:29
Is the geo-coding resolved? Germany isn't ingesting.

**Comment by attwad** [comment] 2020-09-28 11:42
Parser didn't run since I submitted the fix this morning, I just trigerred a run now and it seems to be ingesting fine 👍

**Comment by Mougk** [comment] 2020-09-28 11:47
Checked in: https://curator.ghdsi.org/cases (20k only), should be: ~286k

**Comment by attwad** [comment] 2020-09-28 11:49
It *is* ingesting as we are commenting now ;) give it a bit of time plz

**Comment by Mougk** [comment] 2020-10-01 21:30
@calremmel

**Comment by attwad** [comment] 2020-10-02 06:39
Germany doesn't provide per-case IDs.

**Comment by Mougk** [comment] 2020-10-02 06:41
Ok. Just to confirm: FID is updated each day and does not correspond to a particular case?

<img width="1225" alt="Screenshot 2020-10-02 at 07 40 46" src="https://user-images.githubusercontent.com/8478551/94895112-9fe86800-0482-11eb-96cf-82f7c3d58220.png">

**Comment by attwad** [comment] 2020-10-02 06:46
wellll maybe? There's no documentation on that field, it says unique ID but we don't know how it's updated/what it represents, if you or anyone can find it in their docs (I couldn't) and if it means what we want then we could change the parser to read this field as well if.

**Comment by Mougk** [comment] 2020-10-02 07:16
Had a look and could not find clear documentation. It does seem though that these ID's are changing. Germany may be a case where (to update cases) we would need to re-upload (ingest) the dataset each day if we can solution the time out issues.

**Comment by Mougk** [comment] 2020-10-02 07:16
@outbreakprepared may know what's up with the object ID's

**Comment by calremmel** [comment] 2020-10-02 13:32
Should I wait for more information on this? Standing by in case any changes are needed with the parsing code.

**Comment by z023** [comment] 2020-10-02 13:43
Yes I'm setting up the sources assuming no unique IDs.

**Comment by Mougk** [comment] 2020-12-15 14:00
@calremmel @AnyaLindstromBattle @fojackson8  I had another look at the data. The Column "
"Refdatum" is date of onset of disease IF "IstErkrankung" shows a "1".

Can that be changed in the parser? Also, what does that mean for backfilling given no UID? @z023

**Comment by z023** [comment] 2020-12-15 14:10
It might mean having to delete all the Germany data and do a total backfill. I have been concerned that with no UUIDs and little case information there is just no way of knowing if there are duplicates being ingested.

**Comment by AnyaLindstromBattle** [comment] 2020-12-15 14:14
Should definitely be implementable at parser level, will tackle now.

**Comment by AnyaLindstromBattle** [comment] 2020-12-15 14:30
@Mougk by 'date of onset of disease' do you mean date of first symptoms? Or something else? Also, where did you find the documentation for this?

**Comment by Mougk** [comment] 2020-12-15 14:32
Documentation here: https://www.arcgis.com/home/item.html?id=f10774f1c63e40168479a1feb6c7ca74

"Referenzdatum: Erkrankungsdatum bzw. wenn das nicht bekannt ist, das Meldedatum" - date of symptom onset, date of first symptoms.

**Closed** 2020-12-16 14:21 UTC
Labels: Importer
