### ISSUE TITLE
Remove top nav bar: remove cases, aggregates, history, fresheness, rank, synch

### ISSUE THREAD

**Issue by dakrownie** [globaldothealth/list#1061] opened 2020-09-16 16:15 UTC
[Link to beta testing blocker list](https://docs.google.com/spreadsheets/d/1wM6se-GPNic3xxyggXPEsk0W6qMo6zl_RRcEwU6OcoU/edit#gid=1506108781)

**Comment by sratcliffe118** [comment] 2020-09-16 22:20
duplicate of #1084

**Closed by sratcliffe118** 2020-09-16 22:20 UTC
Labels: P0: Critical path blocker
