### ISSUE TITLE
Consider backing up cases in caserevisions on delete

### ISSUE THREAD

**Issue by khmoran** [globaldothealth/list#797] opened 2020-08-14 18:27 UTC
@scarpino mentioned yesterday that it may be useful to have history for cases that have been deleted. When a case is deleted, we should consider backing it up in the caserevisions case like we do for edited cases.

**Comment by allysonjp715** [comment] 2020-09-10 16:08
Duplicate of #933

**Closed by allysonjp715** 2020-09-10 16:08 UTC
Labels: Data
