### ISSUE TITLE
Linelist search: Ability to search based on CaseID

### ISSUE THREAD

**Issue by sratcliffe118** [globaldothealth/list#639] opened 2020-07-27 11:54 UTC
Feature: Curators should be able to search the linelist based on the case ID

E.g. Currently searching the case ID (5f1b45499fd4e9dc80dc64af) returns no results. Case ID should be a searchable field within the linelist

CUJ: Supports the use case of curators discussing and needing to find, update or delete a specific case where they just have the ID

**Comment by attwad** [comment] 2020-07-29 19:18
Dupe of #679 , closing.

**Closed by attwad** 2020-07-29 19:18 UTC
Labels: Curator Portal, P1 Launch blocker
