### ISSUE TITLE
Negative COVID test results to also be ingested

### ISSUE THREAD

**Issue by z023** [globaldothealth/list#1047] opened 2020-09-16 10:02 UTC
Could cases whose COVID test results are negative also be ingested? E.g. Estonia source data contains positive and negative test results (https://opendata.digilugu.ee/opendata_covid19_test_results.csv).

**Comment by attwad** [comment] 2020-09-16 10:04
Not until the schema supports it: https://github.com/globaldothealth/list/issues/457

**Comment by allysonjp715** [comment] 2020-09-16 13:23
Duplicate of #457

**Closed by allysonjp715** 2020-09-16 13:23 UTC
Labels: Infrastructure, P2: Nice to have
